#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"

# Install packages
if [[ "$(uname)" == "Linux" ]]; then
    sudo apt-get update
    sudo apt-get install -y eza lnav bat ripgrep highlight vim neovim grc

    # Debian/Ubuntu ship bat's binary as `batcat`; expose it as `bat` too
    mkdir -p ~/bin
    ln -sf "$(command -v batcat)" ~/bin/bat
else
    brew install exa
    brew install lnav
    brew install bat
    brew install ripgrep
    brew install highlight
fi

# Install Vim-Plug
curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# Link nvim to vim
ln -sf ../.vim ~/.config/nvim
ln -sf ../.vimrc ~/.vim/init.vim

# Add julian_bash to bashrc
grep -qxF 'source ~/.dotfiles/julian_bash.sh' ~/.bashrc || echo "source ~/.dotfiles/julian_bash.sh" >> ~/.bashrc
